/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.github.jvalentino

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        when:
        true

        then:
        true
    }
}
